reference_fa: 00.data/reference/Zm-B73-REFERENCE-NAM-5.0.fa
genome_ref: Zm-B73
cactus_bw_alignment: 00.data/cactus_algn/Zm-B73_vs_18_non_maize_lineages.renamed_chrom.bw
cactus_genome_number: 10
cactus_MAF: 00.data/cactus_algn/evolverPlants_all_genomes.maf
gene_annotation_bed_file: 00.data/bed_files/Zm-B73-REFERENCE-NAM_Zm00001eb.1.all_nc_coding_genes.bed
scATAC_bed_file: 00.data/bed_files/maize_scATAC_atlas_all_ACRs.v5.sorted.bed
bed_base: zea_mays_v5
protein_fasta: 00.data/protein_fa/Zm-B73_5.0.protein.longest.fa
RNA_samples:
    2-4_mm_from_tip_of_ear_primordium
    MZ
    RNA_B73_root
    6-8_mm_from_tip_of_ear_primordium
    Germinating_Kernels
    pericarp_aleurone
    silks
    Cortex
    GROWTH_ZONE
    PR
    SR
    embryos_20DAP
    Internode_6-7
    EMBRYOS
    Internode_7-8
    STOMATAL_DIVISION_ZONE
    endosperm_crown
    mature_female_spikelets
    SYMMETRICAL_DIVISION_ZONE
    EZ
    MATURE_LEAF_TISSUE_leaf
    RNA_B73_ear
    Vegetative_Meristem_Surrounding_Tissue
    Mature_pollen
    RNA_B73_leaf

chip_seq_samples:
    zea_mays_type_Ch_name_H3K36me3_tis_ear_broad_reproducible_peaks_all:
    zea_mays_type_Ch_name_H3K36me3_tis_leaf_broad_reproducible_peaks_all:
    zea_mays_type_Ch_name_H3K36me3_tis_root_broad_reproducible_peaks_all:
    zea_mays_type_Ch_name_H3K4me1_tis_ear_broad_reproducible_peaks_all:
    zea_mays_type_Ch_name_H3K4me1_tis_leaf_broad_reproducible_peaks_all:
    zea_mays_type_Ch_name_H3K4me1_tis_root_broad_reproducible_peaks_all:
    zea_mays_type_Ch_name_H3K4me3_tis_ear_narrow_reproducible_peaks_all:
    zea_mays_type_Ch_name_H3K4me3_tis_leaf_narrow_reproducible_peaks_all:
    zea_mays_type_Ch_name_H3K4me3_tis_root_narrow_reproducible_peaks_all:
    zea_mays_type_Ch_name_H3K56ac_tis_ear_narrow_reproducible_peaks_all:
    zea_mays_type_Ch_name_H3K56ac_tis_leaf_narrow_reproducible_peaks_all:
    zea_mays_type_Ch_name_H3K56ac_tis_root_narrow_reproducible_peaks_all:
